version: '3.5'

services:
  postgres:
    container_name: db
    image: postgres
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    restart: always